[package]
name = "hammer-and-sample"
version = "0.1.0"
edition = "2021"

[lib]
test = false

[dependencies]
rand = { version = "0.8", default-features = false }
rayon = { version = "1.5", optional = true }

[dev-dependencies]
rand_distr = "0.4"
rand_pcg = "0.3"
